global using AutoBogus;
global using Bunit;
global using DynamoLeagueBlazor.Server.Models;
global using FluentAssertions;
global using FluentValidation.TestHelper;
global using MockHttp;
global using Moq;
global using MudBlazor;
global using System.Net;
global using System.Net.Http.Json;
global using Xunit;
global using static DynamoLeagueBlazor.Server.Models.Player;
global using static DynamoLeagueBlazor.Tests.FakeFactory;
global using static DynamoLeagueBlazor.Tests.IntegrationTesting;
