global using AutoBogus;
global using Bunit;
global using FluentAssertions;
global using FluentValidation.TestHelper;
global using MockHttp;
global using Moq;
global using System.Net;
global using Xunit;
global using static DynamoLeagueBlazor.Tests.FakeFactory;
global using static DynamoLeagueBlazor.Tests.IntegrationTesting;
